name: ci

on:
  push:
    branches:
      - lab-1
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on:  windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run clang-format
        run: |
          clang-format -i -style=file **/*.cpp **/*.h 
          git diff --exit-code
        continue-on-error: true

      - name: Run clang-tidy
        run: |
          for file in *.cpp; do
            clang-tidy "$file"
          done

      - name: Run tests
        run: ctest --tests-dir build
